
import belfastmet.P2A1.model.Employee;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
import jframes.MainFrame;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
    
   //Variables declared from Employee 
   static ResultSet rs;
   static int EmployeeID;
   static String firstName;
   static String lastName;
   static String accessLevel;
   static String address;
   static String dob;
   static String city;
   static String email;
   static String contactNum;
   static String userName;

   static String password;
   
   //Creates an employee object called user
   private Employee user;
   
   

    public void loginResultSet(ResultSet rs){

          
        
        try{  
                //Uses the resultset to assign the values of each DB Field to its 
                //Corresponding Variable
                EmployeeID = rs.getInt("EmployeeID"); 
                firstName = rs.getString("FirstName");
                lastName = rs.getString("LastName");
                accessLevel = rs.getString("AccessLevel");
                address = rs.getString("Address");
                city = rs.getString("City");
                dob = rs.getString("DOB");
                email = rs.getString("Email");
                contactNum = rs.getString("ContactNum");
                
                //Instantiates an Object of type Employee called User.
                user = new Employee(EmployeeID, firstName, lastName, accessLevel, address, null, email, contactNum);

                
                userName = rs.getString("Username"); 
                password = rs.getString("Password");
                
                System.out.println("_________________________________"); 
                System.out.println("ID           : "+ EmployeeID); 
                System.out.println("AccessLevel         : "+accessLevel);
                System.out.println("Password     : "+password);
                System.out.println("Name         : " + firstName + " " + lastName);
                System.out.println("Email        : " + email);
                System.out.println("Date of Birth: "+ dob);
                System.out.println("Contact Number: "+ contactNum);
                
                System.out.println("_________________________________");
                
            
        } catch(Exception e){
            // handle here ...
        }
    }
   
   
   
    /**
     * Creates new form Login
     */
    public Login() {  
       initComponents();  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContentPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Employee Portal");

        lblUsername.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPassword.setText("Password:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername)
                                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblUsername))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblPassword))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnLogin)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContentPaneLayout = new javax.swing.GroupLayout(pnlContentPane);
        pnlContentPane.setLayout(pnlContentPaneLayout);
        pnlContentPaneLayout.setHorizontalGroup(
            pnlContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentPaneLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlContentPaneLayout.setVerticalGroup(
            pnlContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        
     try {
           ////Connects the User to the database upon login
           String dataSourceName = "P2A1DB.accdb;";
           String dbURL = "jdbc:ucanaccess://";
           String conStr = dbURL + dataSourceName + ";";
           Connection dbconn = DriverManager.getConnection(conStr); 
           Statement stmt = dbconn.createStatement( );

           System.out.println("Starting Project");

           System.out.println("About to connect to DB ....");
           
            
           System.out.println("Database connected..");
           
           //The username and password variables are collected using the text boxes for username and password
           String userName = txtUsername.getText();
           char[] userPasswordCharacters = pwdPassword.getPassword();
    
           //The string builder concatenates the individual chars in the array to 
           //Create a full password that can be stored in a string.
           StringBuilder strBuilder = new StringBuilder();
           strBuilder.append(userPasswordCharacters);
    
           //The Full string password.
           String userPassword = strBuilder.toString();
    
           //The SQL statement that checks that the username and password supplied by the user
           //matches a record held in the database.
           System.out.println("Name is: " + userName + " Password is: " + userPassword);
           String SQL = "SELECT * FROM Employee WHERE Username = '"+userName+"' AND Password = '"+userPassword+"' ;";    
           ResultSet rs = stmt.executeQuery(SQL);
           
           //If the values provided are not equal to a record held in the database then an error messagge is outputted.
            if(!rs.next()){ 
               JOptionPane.showMessageDialog(rootPane, "Username OR Password INCORRECT, Try Again!");
            }
            else
            {
               //If the users details match a record in the DB then the method loginResultSet is called that retrieves 
               //the users employee details and stores them in the corresponding variables.
               loginResultSet(rs); 
               System.out.println(accessLevel + address);
                
               //In addition to this a new Employee object called user is created that allows for the values stored
               //in the result set to be passed through all of the corresponding forms after logging in.
               //Upon successful login all employees regardless of their access level are redirected to the MainFrame form.
                MainFrame mainFrame = new MainFrame(user);
                mainFrame.setVisible(true);
                this.setVisible(false);
                                      
            }

        }
        catch(SQLException sqlex){
            //Try catch used to catch and document errors in this instance if the database fails to connect.
            System.out.println("DB Connection problem."+sqlex.toString());
            System.exit(1);
        }
        catch (Exception e){
            
        }
     

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContentPane;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
